title: Nazar Biletskyy 20092975
logo: /assets/img/headshot_circle.png
description: "Assessing the Impact of Data Masking Techniques on Healthcare Database Systems Performance"
gif_image: /assets/img/lilgit.gif
show_downloads: true
theme: jekyll-theme-minimal
