title: Nazar Biletskyy 20092975
logo: /assets/img/fotor-2024020723239.png
description: "Assessing the Impact of Data Masking Techniques on Healthcare Database Systems Performance"
show_downloads: true
theme: jekyll-theme-minimal
